### ISSUE TITLE
AU Linux kernel autumn 2016 запрос на проверку vsd1 Liza Tretyakova

### ISSUE THREAD

**Issue by LizaTretyakova-zz** [LizaTretyakova/au-linux-kernel-autumn-2016#2]
https://github.com/LizaTretyakova/au-linux-kernel-autumn-2016/commit/dfdd55e7535207125afd2dd2aa6d27b200fb55d7

**Comment by eabatalov** [comment]
Привет.
Есть небольшие помарки. 95% за задачу.
