### ISSUE TITLE
AU Linux kernel autumn 2016 запрос на проверку vsd2 Liza Tretyakova 

### ISSUE THREAD

**Issue by LizaTretyakova-zz** [LizaTretyakova/au-linux-kernel-autumn-2016#3]
https://github.com/LizaTretyakova/au-linux-kernel-autumn-2016/commit/066a1ebb5e690b2c65f0723181a11954ea556fd1

**Comment by LizaTretyakova-zz** [comment]
Somewhere in the mmap.

**Comment by eabatalov** [comment]
Please don't forget to assign issue to me.

**Comment by eabatalov** [comment]
You need to add vsd_dev_vma_open() call into vsd_dev_mmap() because vsd_dev_vma_open isn't called on the first mmap but vsd_dev_vma_close() is called on the unmap of the first mmap.

**Comment by eabatalov** [comment]
У тебя довольно много ошибок в решении.
Придется поставить 60% за ДЗ.
Спроси вопросы на паре, если нужно уточнить какие-то ошибки.
