### ISSUE TITLE
AU Linux kernel autumn 2016 запрос на проверку vsd4 Третьяковой Лизы

### ISSUE THREAD

**Issue by LizaTretyakova-zz** [LizaTretyakova/au-linux-kernel-autumn-2016#5]
https://github.com/LizaTretyakova/au-linux-kernel-autumn-2016/commit/6cfe87133a84096439a4bad2af2cb390b457fd58

**Comment by LizaTretyakova-zz** [comment]
Пара вещей:
1. Коммит такой странный, потому что это я так полльзуюсь командой `git rebase -i`, извините.
2. Оно не то чтобы проходит тесты...)

**Comment by eabatalov** [comment]
Привет. Постарайся в следующий раз нормально поребейситься, чтобы были только твои изменения без стартового кода. А то читать не удобно, мягко говоря.

А вобще по коду... ну что-то как-то совсем мало и очень далеко от задумки. 10% могу  за userspace поставить. Надеюсь, разбор кода на паре сделал чуть понятнее смысл задания.
